
name: CI
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    
env:
  NIXPKGS_ALLOW_UNFREE: 1


jobs:
  ci:
    name: Keccak implementation
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ci.yml
    secrets: inherit 
  ec:
    name: EasyCrypt
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ec.yml
    secrets: inherit 
  bench:
    name: Benchmarks
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/bench.yml
    secrets: inherit 

